package com.londonhydro.utils;

public interface MoveInConstant {
	
	String MOVEIN_CUSTOMER_TYPE_PERSON="1";
	String MOVEIN_CUSTOMER_TYPE_ORGANIZATION="2";
	String MOVEIN_NEW_EMAIL_CATEGORY="PRIMARY EMAIL";
	String MOVEIN_ID_TYPE_STUDENT="STUDENT_ID";
	String MOVEIN_BUSINESS_CATEGORY_INC="Incorporated";
	String MOVEIN_BUSINESS_CATEGORY_PVT="Private";
	String MOVEIN_BUSINESS_ID="REGISTRATION";
	String MOVEIN_COUNTRY_CODE="CA";
}
